language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.12
  - DJANGO=1.5.7
  - DJANGO=1.6.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q . --use-mirrors
  - pip install -q mock --use-mirrors
  - pip install -q pep8 --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 eveigb"
script:
  - python setup.py test
