language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.8
  - DJANGO=1.5.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q . --use-mirrors
  - pip install -q mock --use-mirrors
  - pip install -q pep8 --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
script:
  - python setup.py test